Repository add-ons/service.iptv.manager, pull requests merged in 2020-05, with the labels that each got.

#3 Implement socket callback
  Makefile
  README.md
  addon.xml
  default.py
  resources/icon.png
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/functions.py
  resources/lib/kodiutils.py
  resources/lib/modules/addon.py
  resources/lib/modules/iptvsimple.py
  resources/lib/service.py
  resources/settings.xml
Labels: enhancement

#4 Assorted fixes
  .pylintrc
  resources/lib/kodiutils.py
  resources/lib/modules/addon.py
Labels: enhancement

#5 Add port to given URI
  README.md
  resources/lib/modules/addon.py
Labels: documentation, enhancement

#8 Add CI flows
  .github/workflows/addon-check.yml
  .github/workflows/ci.yml
  .gitignore
  .pylintrc
  addon.xml
  resources/lib/modules/addon.py
  tests/userdata/addon_settings.json
  tests/userdata/global_settings.json
  tests/xbmc.py
  tests/xbmcgui.py
Labels: testing

#9 Implement refreshing logic
  .gitignore
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/functions.py
  resources/lib/kodiutils.py
  resources/lib/modules/addon.py
  resources/lib/modules/iptvsimple.py
  resources/lib/service.py
  resources/settings.xml
Labels: enhancement

#10 Add integration test
  resources/lib/kodiutils.py
  resources/lib/modules/addon.py
  tests/__init__.py
  tests/mocks/plugin.video.example/addon.xml
  tests/mocks/plugin.video.example/plugin.py
  tests/mocks/plugin.video.example/resources/settings.xml
  tests/test_integration.py
  tests/test_iptvsimple.py
  tests/userdata/addon_settings.json
  tests/xbmc.py
  tests/xbmcextra.py
Labels: testing

#12 Update documentation
  INTEGRATION.md
  README.md
  addon.xml
  resources/icon.png
  resources/screenshot01.jpg
  resources/screenshot02.jpg
  resources/screenshot03.jpg
  resources/screenshot04.png
  resources/screenshot05.png
  resources/screenshot06.png
Labels: documentation

#20 Add an entry to "Program add-ons"
  addon.xml
  default.py
  resources/lib/functions.py
Labels: enhancement

#22 Create a new icon
  resources/icon.png
Labels: enhancement

#19 Allow playing on demand items from the PVR Guide
  .gitignore
  addon.xml
  context.py
  requirements.txt
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/functions.py
  resources/lib/kodiutils.py
  resources/lib/modules/addon.py
  resources/lib/modules/contextmenu.py
  resources/lib/modules/iptvsimple.py
  tests/mocks/plugin.video.example.two/addon.xml
  tests/mocks/plugin.video.example.two/plugin.py
  tests/mocks/plugin.video.example.two/resources/settings.xml
  tests/mocks/plugin.video.example/plugin.py
  tests/test_integration.py
  tests/userdata/addon_settings.json
  tests/xbmc.py
  tests/xbmcextra.py
  tests/xbmcgui.py
Labels: enhancement
