Repository add-ons/service.iptv.manager, pull requests merged in 2020-11, with the labels that each got.

#45 Add a release workflow
  .github/workflows/release.yml
  Makefile
Labels: release, testing

#54 Allow passing credits with the EPG data
  .pylintrc
  resources/lib/modules/iptvsimple.py
  tests/xbmc.py
  tests/xbmcgui.py
  tests/xbmcvfs.py
Labels: enhancement

#55 Run tests on Python 3.9
  .github/workflows/ci.yml
  tox.ini
Labels: testing
