Repository add-ons/service.iptv.manager, pull requests merged in 2021-01, with the labels that each got.

#58 Improve tests and run tests on Windows
  .env.example
  .gitattributes
  .github/workflows/ci.yml
  .gitignore
  Makefile
  requirements.txt
  resources/lib/functions.py
  resources/lib/kodiutils.py
  resources/lib/modules/addon.py
  resources/lib/service.py
  tests/__init__.py
  tests/check_for_unused_translations.py
  tests/home/addons/inputstream.adaptive/addon.xml
  tests/home/addons/plugin.video.example.two/__init__.py
  tests/home/addons/plugin.video.example.two/addon.xml
  tests/home/addons/plugin.video.example.two/plugin.py
  tests/home/addons/plugin.video.example.two/resources/settings.xml
  tests/home/addons/plugin.video.example/__init__.py
  tests/home/addons/plugin.video.example/addon.xml
  tests/home/addons/plugin.video.example/plugin.py
  tests/home/addons/plugin.video.example/resources/settings.xml
  tests/home/addons/pvr.iptvsimple/addon.xml
  tests/home/userdata/addon_data/plugin.video.example.two/settings.xml
  tests/home/userdata/addon_data/plugin.video.example/settings.xml
  tests/home/userdata/addon_data/pvr.iptvsimple/settings.xml
  tests/home/userdata/guisettings.xml
  tests/test_integration.py
  tests/test_service.py
  tests/userdata/addon_settings.json
  tests/userdata/global_settings.json
  tests/xbmc.py
  tests/xbmcaddon.py
  tests/xbmcextra.py
  tests/xbmcgui.py
  tests/xbmcplugin.py
  tests/xbmcvfs.py
  tox.ini
Labels: testing

#65 Add Romanian strings.
  resources/language/resource.language.ro_ro/strings.po
Labels: translations

#66 Testing improvements
  .gitignore
  requirements.txt
  tests/home/addons/plugin.video.example.two/plugin.py
  tests/home/addons/plugin.video.example/plugin.py
  tests/test_integration.py
Labels: testing

#70 Fix empty space in start and stop fields when no timezone was specified
  resources/lib/modules/iptvsimple.py
  tests/home/addons/plugin.video.example.two/plugin.py
  tests/home/addons/plugin.video.example/plugin.py
Labels: bug

#68 Add support for #KODIPROP
  resources/lib/modules/iptvsimple.py
  tests/home/addons/plugin.video.example/plugin.py
  tests/test_integration.py
Labels: enhancement

#71 Verify xmltv output against the xmltv.dtd
  resources/lib/modules/addon.py
  resources/lib/modules/iptvsimple.py
  tests/home/addons/plugin.video.example.three/plugin.py
  tests/home/addons/plugin.video.example/plugin.py
  tests/test_integration.py
  tests/xmltv.dtd
Labels: enhancement, testing

#73 Fix/improve the add-on description and summary
  addon.xml
Labels: documentation
